# Generated by Django 3.1.7 on 2021-03-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210312_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cast'),
        ),
    ]
