# Generated by Django 3.1.7 on 2021-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_genre_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
