# Generated by Django 3.1.7 on 2021-03-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210313_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='award',
            name='movie',
        ),
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.award')),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cast')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.movie')),
            ],
        ),
    ]
