# Generated by Django 3.1.7 on 2021-03-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210313_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardcategory',
            options={'verbose_name_plural': 'Award Categories'},
        ),
    ]
