# Generated by Django 3.1.7 on 2021-03-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210313_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='first_year',
            field=models.IntegerField(default=1929),
            preserve_default=False,
        ),
    ]
