# Generated by Django 3.1.7 on 2021-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_award_first_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
