# Generated by Django 3.1.7 on 2021-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210313_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country',
            field=models.CharField(default='USA', max_length=30),
            preserve_default=False,
        ),
    ]
