# Generated by Django 3.1.7 on 2021-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210317_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardcategory',
            name='isWinner',
            field=models.BooleanField(default=False),
        ),
    ]
