# Generated by Django 3.1.7 on 2021-03-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_awardcategory_iswinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
