# Generated by Django 3.1.7 on 2021-03-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_person_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp',
            field=models.ImageField(blank=True, upload_to='photos/pp'),
        ),
    ]
